# only works on cpp Not jupyter_c_kernel and TOO HEAVY

# TO BUILD
# > docker build -f .devcontainer/Dockerfile_cpp -t who0joe/c-py:cpp .

FROM python:3.11.5-bookworm

############################################## TimeZone Config ##############################################

# Set the timezone to KST
ENV TZ=Asia/Seoul
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

############################################## C Config ##############################################

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
    cmake \
    && rm -rf /var/lib/apt/lists/*

############################################## Python Config ##############################################

# Set the working directory to /workspace
ENV PYTHONPATH "${PYTHONPATH}:/workspace"

# Install Python packages
RUN python -m pip install --upgrade pip \
    && pip install ipykernel ipywidgets \
    black \
    numpy pandas \
    psycopg2 \
	httpx websockets \
    fastapi uvicorn uvloop ujson


RUN wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh && \
    bash Miniconda3-latest-Linux-x86_64.sh -b -p /opt/miniconda && \
    rm Miniconda3-latest-Linux-x86_64.sh

# 환경 변수 설정
ENV PATH="/opt/miniconda/bin:${PATH}"

# Conda 가상 환경을 만들고 활성화합니다.
# RUN conda create -n cling ; \
#     conda activate cling

# mamba를 설치합니다.
RUN conda install -c conda-forge mamba

# 필요한 패키지 또는 파이썬 라이브러리를 설치합니다.
RUN mamba install xeus-cling -c conda-forge


############################################## Git Config ##############################################

RUN git config --global core.ignorecase false; \
 	git config --global core.autocrlf true; \
    git config --global pull.rebase false; \
    git config --global user.email "rocenrol@naver.com"; \
    git config --global user.name "Hooyoung"



#@@@@@ Additonal Config @@@@@#

# RUN apt-get update \
#     && apt-get install -y --no-install-recommends \
#     {APT-PACKAGE} \
#     && rm -rf /var/lib/apt/lists/*

# RUN pip install --upgrade pip \
#     && pip install \
#     {PIP-PACKAGE}